import { ExtendedCourseType } from "@/schema/course.schema";

export const mockTeacherCourses: ExtendedCourseType[] = [
  {
    id: 1,
    title: "Complete Web Development Bootcamp 2024",
    courseDescription: {
      headline: "Master full-stack web development from scratch",
      targetKnowledges: ["HTML", "CSS", "JavaScript", "React", "Node.js", "MongoDB"],
      requirements: ["Basic computer skills", "Passion for learning"],
      suitableParticipants: ["Beginners", "Career changers", "Students"],
      detail: "This comprehensive course will take you from zero to hero in web development. Learn modern technologies and build real-world projects.",
    },
    price: 99.99,
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
    teacher: {
      id: "teacher-1",
      fullName: "John Smith",
      email: "john.smith@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "United States",
      status: "active",
    },
    rating: 4.8,
    slug: "complete-web-development-bootcamp-2024",
    updatedAt: new Date("2024-10-15"),
    countStudent: 1250,
    category: {
      id: "cat-1",
      parentId: null,
      title: "Web Development",
      slug: "web-development",
    },
  },
  {
    id: 2,
    title: "Advanced React & Redux - Complete Guide",
    courseDescription: {
      headline: "Build modern web applications with React and Redux",
      targetKnowledges: ["React Hooks", "Redux Toolkit", "TypeScript", "Testing"],
      requirements: ["JavaScript fundamentals", "Basic React knowledge"],
      suitableParticipants: ["Intermediate developers", "React enthusiasts"],
      detail: "Deep dive into advanced React concepts and state management with Redux. Build production-ready applications.",
    },
    price: 79.99,
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
    teacher: {
      id: "teacher-1",
      fullName: "John Smith",
      email: "john.smith@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "United States",
      status: "active",
    },
    rating: 4.9,
    slug: "advanced-react-redux-complete-guide",
    updatedAt: new Date("2024-11-01"),
    countStudent: 856,
    category: {
      id: "cat-1",
      parentId: null,
      title: "Web Development",
      slug: "web-development",
    },
  },
  {
    id: 3,
    title: "Node.js - The Complete Backend Development Course",
    courseDescription: {
      headline: "Master backend development with Node.js and Express",
      targetKnowledges: ["Node.js", "Express.js", "REST APIs", "MongoDB", "Authentication"],
      requirements: ["JavaScript basics", "Understanding of web fundamentals"],
      suitableParticipants: ["Web developers", "Backend enthusiasts"],
      detail: "Learn to build scalable backend applications with Node.js. Cover everything from basics to advanced topics.",
    },
    price: 89.99,
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
    teacher: {
      id: "teacher-1",
      fullName: "John Smith",
      email: "john.smith@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "United States",
      status: "active",
    },
    rating: 4.7,
    slug: "nodejs-complete-backend-development",
    updatedAt: new Date("2024-09-20"),
    countStudent: 642,
    category: {
      id: "cat-2",
      parentId: null,
      title: "Backend Development",
      slug: "backend-development",
    },
  },
  {
    id: 4,
    title: "TypeScript Masterclass - From Beginner to Expert",
    courseDescription: {
      headline: "Learn TypeScript and write better JavaScript code",
      targetKnowledges: ["TypeScript", "Type System", "Generics", "Decorators"],
      requirements: ["JavaScript knowledge"],
      suitableParticipants: ["JavaScript developers", "TypeScript beginners"],
      detail: "Comprehensive TypeScript course covering all features and best practices.",
    },
    price: 69.99,
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
    teacher: {
      id: "teacher-1",
      fullName: "John Smith",
      email: "john.smith@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "United States",
      status: "active",
    },
    rating: 4.8,
    slug: "typescript-masterclass-beginner-expert",
    updatedAt: new Date("2024-10-28"),
    countStudent: 523,
    category: {
      id: "cat-3",
      parentId: null,
      title: "Programming Languages",
      slug: "programming-languages",
    },
  },
  {
    id: 5,
    title: "Next.js 14 - The Complete Developer Guide",
    courseDescription: {
      headline: "Build modern full-stack applications with Next.js 14",
      targetKnowledges: ["Next.js", "Server Components", "App Router", "Server Actions"],
      requirements: ["React knowledge", "JavaScript/TypeScript"],
      suitableParticipants: ["React developers", "Full-stack developers"],
      detail: "Master Next.js 14 with all the latest features including Server Components and Server Actions.",
    },
    price: 94.99,
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
    teacher: {
      id: "teacher-1",
      fullName: "John Smith",
      email: "john.smith@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "United States",
      status: "active",
    },
    rating: 4.9,
    slug: "nextjs-14-complete-developer-guide",
    updatedAt: new Date("2024-11-05"),
    countStudent: 734,
    category: {
      id: "cat-1",
      parentId: null,
      title: "Web Development",
      slug: "web-development",
    },
  },
  {
    id: 6,
    title: "Database Design & SQL Mastery",
    courseDescription: {
      headline: "Learn database design and master SQL queries",
      targetKnowledges: ["SQL", "Database Design", "PostgreSQL", "MySQL", "Normalization"],
      requirements: ["Basic programming knowledge"],
      suitableParticipants: ["Developers", "Data analysts", "Database beginners"],
      detail: "Comprehensive course on database design principles and SQL. Work with real databases.",
    },
    price: 74.99,
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
    teacher: {
      id: "teacher-1",
      fullName: "John Smith",
      email: "john.smith@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "United States",
      status: "active",
    },
    rating: 4.6,
    slug: "database-design-sql-mastery",
    updatedAt: new Date("2024-08-12"),
    countStudent: 491,
    category: {
      id: "cat-4",
      parentId: null,
      title: "Databases",
      slug: "databases",
    },
  },
  {
    id: 7,
    title: "Docker & Kubernetes - DevOps Complete Course",
    courseDescription: {
      headline: "Master containerization and orchestration",
      targetKnowledges: ["Docker", "Kubernetes", "CI/CD", "DevOps practices"],
      requirements: ["Linux basics", "Command line knowledge"],
      suitableParticipants: ["Developers", "DevOps engineers", "System administrators"],
      detail: "Learn Docker and Kubernetes from scratch. Deploy and manage containerized applications.",
    },
    price: 84.99,
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
    teacher: {
      id: "teacher-1",
      fullName: "John Smith",
      email: "john.smith@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "United States",
      status: "active",
    },
    rating: 4.7,
    slug: "docker-kubernetes-devops-complete",
    updatedAt: new Date("2024-09-30"),
    countStudent: 612,
    category: {
      id: "cat-5",
      parentId: null,
      title: "DevOps",
      slug: "devops",
    },
  },
  {
    id: 8,
    title: "Python Programming - From Zero to Hero",
    courseDescription: {
      headline: "Learn Python programming for beginners",
      targetKnowledges: ["Python basics", "OOP", "Data structures", "File handling"],
      requirements: ["No programming experience needed"],
      suitableParticipants: ["Complete beginners", "Career switchers"],
      detail: "Start your programming journey with Python. Perfect for beginners with no prior experience.",
    },
    price: 59.99,
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
    teacher: {
      id: "teacher-1",
      fullName: "John Smith",
      email: "john.smith@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "United States",
      status: "active",
    },
    rating: 4.8,
    slug: "python-programming-zero-to-hero",
    updatedAt: new Date("2024-07-18"),
    countStudent: 1089,
    category: {
      id: "cat-3",
      parentId: null,
      title: "Programming Languages",
      slug: "programming-languages",
    },
  },
  {
    id: 9,
    title: "GraphQL with Node.js - Complete Guide",
    courseDescription: {
      headline: "Build modern APIs with GraphQL",
      targetKnowledges: ["GraphQL", "Apollo Server", "Resolvers", "Schemas"],
      requirements: ["JavaScript", "Node.js basics"],
      suitableParticipants: ["Backend developers", "API developers"],
      detail: "Learn GraphQL from scratch and build powerful APIs with Node.js and Apollo Server.",
    },
    price: 79.99,
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
    teacher: {
      id: "teacher-1",
      fullName: "John Smith",
      email: "john.smith@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "United States",
      status: "active",
    },
    rating: 4.7,
    slug: "graphql-nodejs-complete-guide",
    updatedAt: new Date("2024-10-08"),
    countStudent: 367,
    category: {
      id: "cat-2",
      parentId: null,
      title: "Backend Development",
      slug: "backend-development",
    },
  },
  {
    id: 10,
    title: "AWS Cloud Practitioner - Complete Course",
    courseDescription: {
      headline: "Get started with Amazon Web Services",
      targetKnowledges: ["AWS Services", "Cloud Computing", "EC2", "S3", "Lambda"],
      requirements: ["Basic IT knowledge"],
      suitableParticipants: ["Cloud beginners", "IT professionals", "Developers"],
      detail: "Learn AWS cloud services and prepare for the Cloud Practitioner certification.",
    },
    price: 89.99,
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
    teacher: {
      id: "teacher-1",
      fullName: "John Smith",
      email: "john.smith@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "United States",
      status: "active",
    },
    rating: 4.6,
    slug: "aws-cloud-practitioner-complete",
    updatedAt: new Date("2024-09-05"),
    countStudent: 823,
    category: {
      id: "cat-6",
      parentId: null,
      title: "Cloud Computing",
      slug: "cloud-computing",
    },
  },
];
