import { CategoryType } from "@/schema/category.schema";
import { CourseType } from "@/schema/course.schema";

export const mockCourses: CourseType[] = [
  {
    id: 1,
    title: "Learn Ay - LMS Website With LearnPRESS",
    courseDescription: {
      headline: "Master website development with LearnPress",
      targetKnowledges: ["Web Development", "LearnPress"],
      requirements: ["Basic HTML/CSS"],
      suitableParticipants: ["Developers", "Students"],
      detail: "Complete course on building LMS websites",
    },
    price: 49,
    teacher: {
      id: 1,
      fullName: "Determined-Poitras",
      email: "teacher1@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
    },
    rating: 5.0,
    slug: "learn-ay-lms-website-with-learnpress",
    updatedAt: new Date(),
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 2,
    title: "The Complete THIMPRESS Website Development",
    courseDescription: {
      headline: "Build professional websites with Thimpress",
      targetKnowledges: ["WordPress", "Thimpress"],
      requirements: ["Basic WordPress knowledge"],
      suitableParticipants: ["Web Developers"],
      detail: "Complete guide to Thimpress development",
    },
    price: 59,
    teacher: {
      id: 2,
      fullName: "Determined-Poitras",
      email: "teacher2@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
    },
    rating: 4.8,
    slug: "complete-thimpress-website-development",
    updatedAt: new Date(),
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 3,
    title: "Course Ay LMS Website With LearnPRESS",
    courseDescription: {
      headline: "Advanced LMS development course",
      targetKnowledges: ["LMS Development", "E-Learning"],
      requirements: ["Web Development Basics"],
      suitableParticipants: ["Developers", "Entrepreneurs"],
      detail: "Learn to build complete LMS platforms",
    },
    price: 39,
    teacher: {
      id: 3,
      fullName: "Determined-Poitras",
      email: "teacher3@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
    },
    rating: 4.9,
    slug: "course-ay-lms-website-with-learnpress",
    updatedAt: new Date(),
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 4,
    title: "Learn Ay - LMS Website With LearnPRESS",
    courseDescription: {
      headline: "Intermediate LMS development",
      targetKnowledges: ["WordPress", "Plugin Development"],
      requirements: ["HTML, CSS, JavaScript"],
      suitableParticipants: ["Web Developers"],
      detail: "Intermediate course on LMS development",
    },
    price: 45,
    teacher: {
      id: 1,
      fullName: "Determined-Poitras",
      email: "teacher1@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
    },
    rating: 4.7,
    slug: "learn-ay-lms-intermediate",
    updatedAt: new Date(),
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 5,
    title: "Course Ay LMS Website With LearnPRESS",
    courseDescription: {
      headline: "Professional LMS development",
      targetKnowledges: ["Advanced WordPress", "Custom Themes"],
      requirements: ["WordPress Experience"],
      suitableParticipants: ["Professional Developers"],
      detail: "Professional level LMS development course",
    },
    price: 69,
    teacher: {
      id: 2,
      fullName: "Determined-Poitras",
      email: "teacher2@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
    },
    rating: 5.0,
    slug: "course-ay-lms-professional",
    updatedAt: new Date(),
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 6,
    title: "Course Ay LMS Website With LearnPRESS",
    courseDescription: {
      headline: "Complete LMS solution development",
      targetKnowledges: ["Full Stack", "LMS Architecture"],
      requirements: ["Programming Knowledge"],
      suitableParticipants: ["Experienced Developers"],
      detail: "Complete solution for LMS development",
    },
    price: 79,
    teacher: {
      id: 3,
      fullName: "Determined-Poitras",
      email: "teacher3@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
    },
    rating: 4.9,
    slug: "course-ay-lms-complete",
    updatedAt: new Date(),
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  }
]

export const mockCategories: CategoryType[] = [
  {
    id: 1,
    parentId: null,
    title: "Art & Design",
    slug: "art-design",
  },
  {
    id: 2,
    parentId: null,
    title: "UI/UX Design",
    slug: "ui-ux-design",
  },
  {
    id: 3,
    parentId: null,
    title: "Communication",
    slug: "communication",
  },
  {
    id: 4,
    parentId: null,
    title: "Videography",
    slug: "videography",
  },
  {
    id: 5,
    parentId: null,
    title: "Photography",
    slug: "photography",
  },
  {
    id: 6,
    parentId: null,
    title: "Marketing",
    slug: "marketing",
  },
  {
    id: 7,
    parentId: null,
    title: "Content Writing",
    slug: "content-writing",
  },
  {
    id: 8,
    parentId: null,
    title: "Finance",
    slug: "finance",
  },
  {
    id: 9,
    parentId: null,
    title: "Science",
    slug: "science",
  },
  {
    id: 10,
    parentId: null,
    title: "Video Editing",
    slug: "video-editing",
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Guy Hawkins",
    content: "I would gladly pay over 600 dollars for EduPress. We have no regrets! EduPress is worth much more than I paid. I would like to personally thank you for your outstanding product.",
    avatar: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 2,
    name: "Dianne Russell",
    content: "I would gladly pay over 600 dollars for EduPress. We have no regrets! EduPress is worth much more than I paid. I would like to personally thank you.",
    avatar: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 3,
    name: "Arlene McCoy",
    content: "I would gladly pay over 600 dollars for EduPress. We have no regrets! EduPress is worth much more than I paid. I would like to personally thank you for your outstanding product.",
    avatar: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 4,
    name: "Guy Hawkins",
    content: "I would gladly pay over 600 dollars for EduPress. We have no regrets! EduPress is worth much more than I paid.",
    avatar: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
]

export const articles = [
  {
    id: 1,
    title: "Best LearnPress WordPress Theme Collection for 2023",
    category: "LearnPress",
    date: "Jan 24, 2023",
    author: "Determined-Poitras",
    readTime: "3 Min Read",
    description: "Looking for an amazing & well-functional LearnPress WordPress Theme?",
    thumbnail: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 2,
    title: "Best LearnPress WordPress Theme Collection for 2023",
    category: "LearnPress",
    date: "Jan 24, 2023",
    author: "Determined-Poitras",
    readTime: "3 Min Read",
    description: "Looking for an amazing & well-functional LearnPress WordPress Theme?",
    thumbnail: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 3,
    title: "Best LearnPress WordPress Theme Collection for 2023",
    category: "LearnPress",
    date: "Jan 24, 2023",
    author: "Determined-Poitras",
    readTime: "3 Min Read",
    description: "Looking for an amazing & well-functional LearnPress WordPress Theme?",
    thumbnail: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
]