import { CategoryType } from "@/schema/category.schema";
import { CourseType, ExtendedCourseType } from "@/schema/course.schema";
import { CourseCurriculumType } from "@/schema/lesson.schema";

export const mockCourses: CourseType[] = [
  {
    id: 1,
    title: "Learn Ay - LMS Website With LearnPRESS",
    courseDescription: {
      headline: "Master website development with LearnPress",
      targetKnowledges: ["Web Development", "LearnPress"],
      requirements: ["Basic HTML/CSS"],
      suitableParticipants: ["Developers", "Students"],
      detail: "Complete course on building LMS websites",
    },
    price: 49,
    teacher: {
      id: "1",
      fullName: "Determined-Poitras",
      email: "teacher1@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "Vietnam",
      status: "active",
    },
    rating: 5.0,
    slug: "learn-ay-lms-website-with-learnpress",
    updatedAt: new Date(),
    isPublished: true,
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 2,
    title: "The Complete THIMPRESS Website Development",
    courseDescription: {
      headline: "Build professional websites with Thimpress",
      targetKnowledges: ["WordPress", "Thimpress"],
      requirements: ["Basic WordPress knowledge"],
      suitableParticipants: ["Web Developers"],
      detail: "Complete guide to Thimpress development",
    },
    price: 59,
    teacher: {
      id: "2",
      fullName: "Determined-Poitras",
      email: "teacher2@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "Vietnam",
      status: "active",
    },
    rating: 4.8,
    slug: "complete-thimpress-website-development",
    isPublished: false,
    updatedAt: new Date(),
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 3,
    title: "Course Ay LMS Website With LearnPRESS",
    courseDescription: {
      headline: "Advanced LMS development course",
      targetKnowledges: ["LMS Development", "E-Learning"],
      requirements: ["Web Development Basics"],
      suitableParticipants: ["Developers", "Entrepreneurs"],
      detail: "Learn to build complete LMS platforms",
    },
    price: 39,
    teacher: {
      id: "3",
      fullName: "Determined-Poitras",
      email: "teacher3@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "Vietnam",
      status: "active",
    },
    rating: 4.9,
    slug: "course-ay-lms-website-with-learnpress",
    isPublished: true,
    updatedAt: new Date(),
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 4,
    title: "Learn Ay - LMS Website With LearnPRESS",
    courseDescription: {
      headline: "Intermediate LMS development",
      targetKnowledges: ["WordPress", "Plugin Development"],
      requirements: ["HTML, CSS, JavaScript"],
      suitableParticipants: ["Web Developers"],
      detail: "Intermediate course on LMS development",
    },
    price: 45,
    teacher: {
      id: "1",
      fullName: "Determined-Poitras",
      email: "teacher1@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "Vietnam",
      status: "active",
    },
    rating: 4.7,
    slug: "learn-ay-lms-intermediate",
    isPublished: true,
    updatedAt: new Date(),
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 5,
    title: "Course Ay LMS Website With LearnPRESS",
    courseDescription: {
      headline: "Professional LMS development",
      targetKnowledges: ["Advanced WordPress", "Custom Themes"],
      requirements: ["WordPress Experience"],
      suitableParticipants: ["Professional Developers"],
      detail: "Professional level LMS development course",
    },
    price: 69,
    teacher: {
      id: "2",
      fullName: "Determined-Poitras",
      email: "teacher2@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "Vietnam",
      status: "active",
    },
    rating: 5.0,
    slug: "course-ay-lms-professional",
    isPublished: true,
    updatedAt: new Date(),
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 6,
    title: "Course Ay LMS Website With LearnPRESS",
    courseDescription: {
      headline: "Complete LMS solution development",
      targetKnowledges: ["Full Stack", "LMS Architecture"],
      requirements: ["Programming Knowledge"],
      suitableParticipants: ["Experienced Developers"],
      detail: "Complete solution for LMS development",
    },
    price: 79,
    teacher: {
      id: "3",
      fullName: "Determined-Poitras",
      email: "teacher3@example.com",
      avatarUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
      role: "teacher",
      emailVerified: true,
      country: "Vietnam",
      status: "active",
    },
    rating: 4.9,
    slug: "course-ay-lms-complete",
    isPublished: false,
    updatedAt: new Date(),
    thumbnailUrl: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  }
]

export const mockCourseDetail: ExtendedCourseType = {
  ...mockCourses[0],
  countStudent: 15,
  category: {
    id: "5",
    parentId: null,
    title: "Photography",
    slug: "photography",
  },
}

// Mock courses for teacher with extended data
export const mockTeacherCourses: ExtendedCourseType[] = [
  {
    ...mockCourses[0],
    countStudent: 1250,
    category: {
      id: "1",
      parentId: null,
      title: "Web Development",
      slug: "web-development",
    },
  },
  {
    ...mockCourses[1],
    countStudent: 450,
    category: {
      id: "2",
      parentId: null,
      title: "WordPress",
      slug: "wordpress",
    },
  },
  {
    ...mockCourses[2],
    countStudent: 890,
    category: {
      id: "1",
      parentId: null,
      title: "Web Development",
      slug: "web-development",
    },
  },
  {
    ...mockCourses[3],
    countStudent: 320,
    category: {
      id: "2",
      parentId: null,
      title: "WordPress",
      slug: "wordpress",
    },
  },
  {
    ...mockCourses[4],
    countStudent: 650,
    category: {
      id: "1",
      parentId: null,
      title: "Web Development",
      slug: "web-development",
    },
  },
  {
    ...mockCourses[5],
    countStudent: 180,
    category: {
      id: "3",
      parentId: null,
      title: "E-Learning",
      slug: "e-learning",
    },
  },
  {
    ...mockCourses[0],
    countStudent: 1250,
    category: {
      id: "1",
      parentId: null,
      title: "Web Development",
      slug: "web-development",
    },
  },
  {
    ...mockCourses[1],
    countStudent: 450,
    category: {
      id: "2",
      parentId: null,
      title: "WordPress",
      slug: "wordpress",
    },
  },
  {
    ...mockCourses[2],
    countStudent: 890,
    category: {
      id: "1",
      parentId: null,
      title: "Web Development",
      slug: "web-development",
    },
  },
  {
    ...mockCourses[3],
    countStudent: 320,
    category: {
      id: "2",
      parentId: null,
      title: "WordPress",
      slug: "wordpress",
    },
  },
]

export const mockCategories: CategoryType[] = [
  {
    id: "1",
    parentId: null,
    title: "Art & Design",
    slug: "art-design",
  },
  {
    id: "2",
    parentId: null,
    title: "UI/UX Design",
    slug: "ui-ux-design",
  },
  {
    id: "3",
    parentId: null,
    title: "Communication",
    slug: "communication",
  },
  {
    id: "4",
    parentId: null,
    title: "Videography",
    slug: "videography",
  },
  {
    id: "5",
    parentId: null,
    title: "Photography",
    slug: "photography",
  },
  {
    id: "6",
    parentId: null,
    title: "Marketing",
    slug: "marketing",
  },
  {
    id: "7",
    parentId: null,
    title: "Content Writing",
    slug: "content-writing",
  },
  {
    id: "8",
    parentId: null,
    title: "Finance",
    slug: "finance",
  },
  {
    id: "9",
    parentId: null,
    title: "Science",
    slug: "science",
  },
  {
    id: "10",
    parentId: null,
    title: "Video Editing",
    slug: "video-editing",
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Guy Hawkins",
    content: "I would gladly pay over 600 dollars for EduPress. We have no regrets! EduPress is worth much more than I paid. I would like to personally thank you for your outstanding product.",
    avatar: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 2,
    name: "Dianne Russell",
    content: "I would gladly pay over 600 dollars for EduPress. We have no regrets! EduPress is worth much more than I paid. I would like to personally thank you.",
    avatar: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 3,
    name: "Arlene McCoy",
    content: "I would gladly pay over 600 dollars for EduPress. We have no regrets! EduPress is worth much more than I paid. I would like to personally thank you for your outstanding product.",
    avatar: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 4,
    name: "Guy Hawkins",
    content: "I would gladly pay over 600 dollars for EduPress. We have no regrets! EduPress is worth much more than I paid.",
    avatar: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
]

export const mockCourseCurriculum: CourseCurriculumType[] = [
  {
    courseId: 1,
    totalDuration: "10h 30m",
    sections: [
      {
        id: 1,
        title: "Introduction to LearnPress",
        lessons: [
          {
            id: 1,
            title: "Welcome to the Course",
            duration: "05:30",
            type: "video",
            isPreview: true,
            isCompleted: false,
            videoUrl: "https://res.cloudinary.com/dndo7fe82/video/upload/v1737527345/zztvh1u93hfhb1ndhb16.mp4",
            content: "Welcome to this comprehensive course on LearnPress. In this introduction, we'll cover what you'll learn and how to get the most out of this course.",
          },
          {
            id: 2,
            title: "Course Overview and Objectives",
            duration: "08:45",
            type: "video",
            isPreview: true,
            isCompleted: false,
            videoUrl: "https://res.cloudinary.com/dndo7fe82/video/upload/v1737527345/zztvh1u93hfhb1ndhb16.mp4",
            content: "Learn about the key objectives and outcomes you can expect from this course.",
          },
          {
            id: 3,
            title: "Setting Up Your Environment",
            duration: "12:20",
            type: "video",
            isPreview: false,
            isCompleted: false,
            videoUrl: "https://res.cloudinary.com/dndo7fe82/video/upload/v1737527345/zztvh1u93hfhb1ndhb16.mp4",
            content: "Step-by-step guide to setting up your development environment for LearnPress.",
          },
          {
            id: 4,
            title: "Quiz: Getting Started",
            duration: "10:00",
            type: "quiz",
            isPreview: false,
            isCompleted: false,
            content: "Test your knowledge on the introduction topics.",
          },
        ],
      },
      {
        id: 2,
        title: "Core Concepts",
        lessons: [
          {
            id: 5,
            title: "Understanding LearnPress Architecture",
            duration: "15:30",
            type: "video",
            isPreview: false,
            isCompleted: false,
            videoUrl: "https://res.cloudinary.com/dndo7fe82/video/upload/v1737527345/zztvh1u93hfhb1ndhb16.mp4",
            content: "Deep dive into the architecture and core concepts of LearnPress.",
          },
          {
            id: 6,
            title: "Creating Your First Course",
            duration: "20:15",
            type: "video",
            isPreview: false,
            isCompleted: false,
            videoUrl: "https://res.cloudinary.com/dndo7fe82/video/upload/v1737527345/zztvh1u93hfhb1ndhb16.mp4",
            content: "Hands-on tutorial on creating your first course with LearnPress.",
          },
          {
            id: 7,
            title: "Managing Lessons and Quizzes",
            duration: "18:40",
            type: "video",
            isPreview: false,
            isCompleted: false,
            videoUrl: "https://res.cloudinary.com/dndo7fe82/video/upload/v1737527345/zztvh1u93hfhb1ndhb16.mp4",
            content: "Learn how to effectively manage lessons and quizzes in your courses.",
          },
          {
            id: 8,
            title: "Assignment: Build a Sample Course",
            duration: "30:00",
            type: "assignment",
            isPreview: false,
            isCompleted: false,
            content: "Create a sample course applying what you've learned so far.",
          },
        ],
      },
      {
        id: 3,
        title: "Advanced Features",
        lessons: [
          {
            id: 9,
            title: "Custom Course Templates",
            duration: "22:10",
            type: "video",
            isPreview: false,
            isCompleted: false,
            videoUrl: "https://res.cloudinary.com/dndo7fe82/video/upload/v1737527345/zztvh1u93hfhb1ndhb16.mp4",
            content: "Master the art of creating custom course templates.",
          },
          {
            id: 10,
            title: "Payment Integration",
            duration: "25:30",
            type: "video",
            isPreview: false,
            isCompleted: false,
            videoUrl: "https://res.cloudinary.com/dndo7fe82/video/upload/v1737527345/zztvh1u93hfhb1ndhb16.mp4",
            content: "Integrate payment gateways for monetizing your courses.",
          },
          {
            id: 11,
            title: "Analytics and Reporting",
            duration: "16:45",
            type: "video",
            isPreview: false,
            isCompleted: false,
            videoUrl: "https://res.cloudinary.com/dndo7fe82/video/upload/v1737527345/zztvh1u93hfhb1ndhb16.mp4",
            content: "Track student progress and generate insightful reports.",
          },
          {
            id: 12,
            title: "Final Quiz",
            duration: "15:00",
            type: "quiz",
            isPreview: false,
            isCompleted: false,
            content: "Comprehensive quiz covering all advanced features.",
          },
        ],
      },
    ],
  },
];

export const articles = [
  {
    id: 1,
    title: "Best LearnPress WordPress Theme Collection for 2023",
    category: "LearnPress",
    date: "Jan 24, 2023",
    author: "Determined-Poitras",
    readTime: "3 Min Read",
    description: "Looking for an amazing & well-functional LearnPress WordPress Theme?",
    thumbnail: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 2,
    title: "Best LearnPress WordPress Theme Collection for 2023",
    category: "LearnPress",
    date: "Jan 24, 2023",
    author: "Determined-Poitras",
    readTime: "3 Min Read",
    description: "Looking for an amazing & well-functional LearnPress WordPress Theme?",
    thumbnail: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
  {
    id: 3,
    title: "Best LearnPress WordPress Theme Collection for 2023",
    category: "LearnPress",
    date: "Jan 24, 2023",
    author: "Determined-Poitras",
    readTime: "3 Min Read",
    description: "Looking for an amazing & well-functional LearnPress WordPress Theme?",
    thumbnail: "https://res.cloudinary.com/dndo7fe82/image/upload/v1757212590/hwqsskrgmbbo9f4gu6uf.webp",
  },
]